zookeeper:
  - host: zookeeper1.kafka.local
    port: 2181
  - host: zookeeper2.kafka.local
    port: 2181
  - host: zookeeper3.kafka.local
    port: 2181
broker:
  - host: broker1.kafka.local
    port: 9092
    protocol: PLAINTEXT
  - host: broker2.kafka.local
    port: 9092
    protocol: PLAINTEXT
  - host: broker3.kafka.local
    port: 9092
    protocol: PLAINTEXT

# truststore:
#   # optional base64 encoded jks truststore when using SSL (create base64 encoded string with 'base64 -w0')
#   jks: ...
#   password: ...

# # optional base64 encoded jaas config (create base64 encoded string with 'base64 -w0')
# jaasConfig: ...

schema_registry:
  enabled: true
  name: schema-registry
  port: 8081
  image:
    repository: confluentinc/cp-schema-registry
    tag: 4.0.0
  ingress:
    enabled: true
    host: kafka-schema-registry.nais.local
  security_protocol: PLAINTEXT
  replication_factor: 3

rest_proxy:
  enabled: true
  name: rest-proxy
  port: 8082
  image:
    repository: confluentinc/cp-kafka-rest
    tag: 4.0.0
  ingress:
    enabled: true
    host: kafka-rest-proxy.nais.local
  security_protocol: PLAINTEXT

