broker:
  - host: broker1.kafka.local
    port: 9092
    protocol: PLAINTEXT
  - host: broker2.kafka.local
    port: 9092
    protocol: PLAINTEXT
  - host: broker3.kafka.local
    port: 9092
    protocol: PLAINTEXT

# # optional base64 encoded jks truststore when using SSL (create base64 encoded string with 'base64 -w0')
# truststore:
#   jks: ...
#   password: ...

# # optional base64 encoded jaas config (create base64 encoded string with 'base64 -w0')
# jaasConfig: ...

schema_registry:
  enabled: true
  name: schema-registry
  port: 8081
  replicas: 1
  master_eligibility: true
  group_id: schema-registry
  image:
    repository: confluentinc/cp-schema-registry
    tag: 5.0.0
  ingress:
    enabled: true
    host:
      - kafka-schema-registry.nais.local
  security_protocol: PLAINTEXT
  replication_factor: 3
# # optional init container to get jaas config from vault
  vault_init:
    enabled: false
    image:
      repository: navikt/vks
      tag: 21
    vks:
      vault_addr: https://vault.nais.local
      auth_path: /kubernetes/nais
      kv_path: /kv/nais/confluent-schema-registry/default
      vault_role: confluent-schema-registry
      secret_dest_path: /var/run/secrets/naisd.io/vault

