zookeeper:
  - host: zookeeper1.kafka.local
    port: 2181
    protocol: PLAINTEXT
  - host: zookeeper2.kafka.local
    port: 2181
    protocol: PLAINTEXT
  - host: zookeeper3.kafka.local
    port: 2181
    protocol: PLAINTEXT
broker:
  - host: broker1.kafka.local
    port: 9092
  - host: broker2.kafka.local
    port: 9092
  - host: broker3.kafka.local
    port: 9092

# truststore:
#   # optional base64 encoded jks truststore when using SSL (create base64 encoded string with 'base64 -w0')
#   jks: ...
#   password: ...

schema_registry:
  enabled: true
  name: schema-registry
  port: 8081
  image:
    repository: confluentinc/cp-schema-registry
    tag: 3.3.0
  ingress:
    enabled: true
    host: kafka-schema-registry.nais.local
  security_protocol: PLAINTEXT

rest_proxy:
  enabled: true
  name: rest-proxy
  port: 8082
  image:
    repository: confluentinc/cp-kafka-rest
    tag: 3.3.0
  ingress:
    enabled: true
    host: kafka-rest-proxy.nais.local
  security_protocol: PLAINTEXT

topics_ui:
  enabled: true
  name: topics-ui
  port: 8000
  proxy: true
  podAnnotations:
    nais.io/logformat: accesslog
  image:
    repository: landoop/kafka-topics-ui
    tag: 0.9.3
  ingress:
    enabled: true
    host: kafka-topics-ui.nais.local
