{{- if .Values.rest_proxy.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "confluent.name" . }}
    component: "{{ .Values.rest_proxy.name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "confluent.rest_proxy.servicename" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "confluent.name" . }}
    component: "{{ .Values.rest_proxy.name }}"
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.rest_proxy.port }}
      targetPort: {{ .Values.rest_proxy.port }}
{{- end -}}
