apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "confluent.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    team: {{ .Values.team }}
  name: {{ template "confluent.schema_registry.serviceaccountname" . }}
