{{- if and .Values.schema_registry.enabled .Values.schema_registry.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ template "confluent.name" . }}
    component: "{{ .Values.schema_registry.name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    team: {{ .Values.team }}
  name: {{ template "confluent.schema_registry.fullname" . }}
spec:
  {{- if .Values.schema_registry.ingress.ingressClassName }}
  ingressClassName: {{ .Values.schema_registry.ingress.ingressClassName }}
  {{- end }}
  rules:
{{- $root := . -}}
{{- range $host := .Values.schema_registry.ingress.host }}
    - host: {{ $host }}
      http:
        paths:
          - backend:
              service:
                name: {{ template "confluent.schema_registry.servicename" $root }}
                port:
                  number: {{ $root.Values.schema_registry.port }}
            path: /
            pathType: Prefix
{{- end }}
{{- end -}}
