{{- if and .Values.schema_registry.enabled .Values.schema_registry.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ template "confluent.name" . }}
    component: "{{ .Values.schema_registry.name }}"
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    team: {{ .Values.team }}
  name: {{ template "confluent.schema_registry.fullname" . }}
spec:
  rules:
{{- $root := . -}}
{{- range $host := .Values.schema_registry.ingress.host }}
    - host: {{ $host }}
      http:
        paths:
          - backend:
              serviceName: {{ template "confluent.schema_registry.servicename" $root }}
              servicePort: {{ $root.Values.schema_registry.port }}
{{- end }}
{{- end -}}
