{{- if or .Values.jaasConfig .Values.truststore -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "confluent.fullname" . }}
  labels:
    app: {{ template "confluent.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.truststore }}
  truststore: {{ .Values.truststore.jks | quote }}
  {{- end -}}
  {{- if .Values.jaasConfig }}
  jaasConfig: {{ .Values.jaasConfig | quote }}
  {{- end -}}
{{- end -}}
